# Generated by Django 4.2.3 on 2023-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=120)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
